#!/bin/bash

echo "[+] Creating npm package..."
npm init -y
echo "[+] Install truffle@latest version..."
npm install --save-dev truffle
echo "[+] Install openzeppelin/contracts@2.5.0 version..."
npm install --save-dev @openzeppelin/contracts@2.5.0
echo "[+] Install openzeppelin/test-helpers@0.5.5 version..."
npm install --save-dev @openzeppelin/test-helpers@0.5.5
#echo "[+] Install openzeppelin/test-environment@0.1.4 version..."
#npm install --save-dev @openzeppelin/test-environment@0.1.4
echo "[+] Install solidity-coverage@latest version..."
npm install --save-dev solidity-coverage
echo "[+] Install mocha@7.1.1 version..."
npm install --save-dev mocha@7.1.1
echo "[+] Install chai@4.2.0 version..."
npm install --save-dev chai@4.2.0
echo "[+] Creating truffle project..."
npx truffle init -y
echo "[!] done with all dependencies"
